name: Build, Test, and Sign

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd controlenginefe
          npm ci  # Install dependencies inside controlenginefe

      - name: Run tests
        run: |
          cd controlenginefe
          npm test  # Run tests inside controlenginefe

      - name: Build project
        run: |
          cd controlenginefe
          npm run build  # Build the project inside controlenginefe


